// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215232706_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("EspecialidadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EstudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instituto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("EstudioId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Domain.Entities.Direccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Esquina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroPuerta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("Domain.Entities.Disponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmprendimientoId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId")
                        .IsUnique();

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("Domain.Entities.DisponibilidadDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<Guid>("DisponibilidadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DisponibilidadId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisponibilidadId");

                    b.HasIndex("DisponibilidadId1");

                    b.ToTable("DisponibilidadDias");
                });

            modelBuilder.Entity("Domain.Entities.Emprendimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DireccionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstudioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExAlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId")
                        .IsUnique();

                    b.HasIndex("EstudioId");

                    b.HasIndex("ExAlumnoId");

                    b.ToTable("Emprendimientos");
                });

            modelBuilder.Entity("Domain.Entities.Estudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Domain.Entities.OfertaLaboral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Salario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("OfertasLaborales");
                });

            modelBuilder.Entity("Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmprendimientoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Domain.Entities.Publicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExAlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExAlumnoId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("Domain.Entities.Respuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExAlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublicacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ExAlumnoId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("Domain.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Costo")
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmprendimientoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmprendimientoId1")
                        .HasColumnType("uuid");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId");

                    b.HasIndex("EmprendimientoId1");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EstudioExAlumno", b =>
                {
                    b.Property<Guid>("EstudiosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExAlumnosId")
                        .HasColumnType("uuid");

                    b.HasKey("EstudiosId", "ExAlumnosId");

                    b.HasIndex("ExAlumnosId");

                    b.ToTable("ExAlumnoEstudio", (string)null);
                });

            modelBuilder.Entity("EstudioOfertaLaboral", b =>
                {
                    b.Property<Guid>("EstudiosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfertasLaboralesId")
                        .HasColumnType("uuid");

                    b.HasKey("EstudiosId", "OfertasLaboralesId");

                    b.HasIndex("OfertasLaboralesId");

                    b.ToTable("OfertaLaboralEstudio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Administradores", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Empresa", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ExAlumno", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.Property<int>("AnioEgreso")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("ExAlumnos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Curso", b =>
                {
                    b.HasOne("Domain.Entities.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Estudio", "Estudio")
                        .WithMany()
                        .HasForeignKey("EstudioId");

                    b.Navigation("Administrador");

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("Domain.Entities.Disponibilidad", b =>
                {
                    b.HasOne("Domain.Entities.Emprendimiento", "Emprendimiento")
                        .WithOne("Disponibilidad")
                        .HasForeignKey("Domain.Entities.Disponibilidad", "EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("Domain.Entities.DisponibilidadDia", b =>
                {
                    b.HasOne("Domain.Entities.Disponibilidad", "Disponibilidad")
                        .WithMany()
                        .HasForeignKey("DisponibilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Disponibilidad", null)
                        .WithMany("Dias")
                        .HasForeignKey("DisponibilidadId1");

                    b.Navigation("Disponibilidad");
                });

            modelBuilder.Entity("Domain.Entities.Emprendimiento", b =>
                {
                    b.HasOne("Domain.Entities.Direccion", "Direccion")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Emprendimiento", "DireccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Estudio", "Estudio")
                        .WithMany()
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ExAlumno", "ExAlumno")
                        .WithMany()
                        .HasForeignKey("ExAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("Estudio");

                    b.Navigation("ExAlumno");
                });

            modelBuilder.Entity("Domain.Entities.Evento", b =>
                {
                    b.HasOne("Domain.Entities.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("Domain.Entities.OfertaLaboral", b =>
                {
                    b.HasOne("Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("Domain.Entities.Emprendimiento", "Emprendimiento")
                        .WithMany()
                        .HasForeignKey("EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("Domain.Entities.Publicacion", b =>
                {
                    b.HasOne("Domain.Entities.ExAlumno", "ExAlumno")
                        .WithMany()
                        .HasForeignKey("ExAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExAlumno");
                });

            modelBuilder.Entity("Domain.Entities.Respuesta", b =>
                {
                    b.HasOne("Domain.Entities.ExAlumno", "ExAlumno")
                        .WithMany()
                        .HasForeignKey("ExAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Publicacion", "Publicacion")
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExAlumno");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Domain.Entities.Servicio", b =>
                {
                    b.HasOne("Domain.Entities.Emprendimiento", "Emprendimiento")
                        .WithMany()
                        .HasForeignKey("EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Emprendimiento", null)
                        .WithMany("servicios")
                        .HasForeignKey("EmprendimientoId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("EstudioExAlumno", b =>
                {
                    b.HasOne("Domain.Entities.Estudio", null)
                        .WithMany()
                        .HasForeignKey("EstudiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ExAlumno", null)
                        .WithMany()
                        .HasForeignKey("ExAlumnosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EstudioOfertaLaboral", b =>
                {
                    b.HasOne("Domain.Entities.Estudio", null)
                        .WithMany()
                        .HasForeignKey("EstudiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OfertaLaboral", null)
                        .WithMany()
                        .HasForeignKey("OfertasLaboralesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Administrador", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Empresa", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Empresa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ExAlumno", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.ExAlumno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Disponibilidad", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("Domain.Entities.Emprendimiento", b =>
                {
                    b.Navigation("Disponibilidad")
                        .IsRequired();

                    b.Navigation("servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
